[project]
name = "graph-challenge"
version = "1.0.0"
description = "Graph challenge"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff==0.11.0",
]
